### ISSUE TITLE
[BUG]: Dependencies conflict with Docker version

### ISSUE THREAD

**Issue by RayyanRiaz** [open-mmlab/Amphion#313]
## Describe the bug
Hi, I tried to run the project via docker as per the instructions in readme. i.e.

```
git clone https://github.com/open-mmlab/Amphion.git
cd Amphion
docker pull realamphion/amphion
docker run --runtime=nvidia --gpus all -it -v .:/app realamphion/amphion
```

However it is not successful. I got the error:
```
ImportError: cannot import name 'Wav2Vec2BertModel' from 'transformers' (/opt/conda/envs/amphion/lib/python3.9/site-packages/transformers/__init__.py)
```

Probably it is due to dependencies mismatch? For instance, `env.sh` has `transformers==4.41.2` and `pip list` inside the container with the [image](https://hub.docker.com/layers/realamphion/amphion/latest/images/sha256-4a7e62f1dce6d6ba05f90e11b28ee5f3eb41c5b409bc69c42fe4632113c475c7?context=explore) shows transformers=4.30.2

**Comment by Athanaze** [comment]
Hello,

Did you find a solution ? I have the same issue.

**Comment by RayyanRiaz** [comment]
@Athanaze I did not proceed, because I was looking for a really light-weight option.

**Comment by unilight** [comment]
I got the same error with transformers version 4.30.2, and when I upgraded it to 4.49 the error was gone.
